name: Update SUMMARY.md

on:
  push:
    branches:
      - main  # Cambia 'main' si usas otra rama

jobs:
  update-summary:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Generar nuevo SUMMARY.md
        run: |
          #!/bin/bash

          SUMMARY_FILE="SUMMARY.md"

          echo "# Table of contents" > "$SUMMARY_FILE"
          echo "" >> "$SUMMARY_FILE"

          generate_summary() {
              local dir="$1"
              local indent="$2"

              # Ordenar directorios y archivos alfabéticamente
              for entry in $(ls -1 "$dir" | sort -f); do
                  local full_path="$dir/$entry"

                  if [[ -d "$full_path" ]]; then
                      echo "${indent}* [$entry]($full_path/README.md)" >> "$SUMMARY_FILE"
                      generate_summary "$full_path" "$indent  "
                  elif [[ -f "$full_path" && "$entry" == *.md && "$entry" != "SUMMARY.md" ]]; then
                      local file_name="${entry%.md}"
                      local title=$(head -n 1 "$full_path" | sed 's/# //')
                      [[ -z "$title" ]] && title="$file_name"

                      # Si el nombre tiene espacios, lo encierra en <>
                      if [[ "$file_name" =~ \  ]]; then
                          file_name="<$full_path>"
                      else
                          file_name="$full_path"
                      fi

                      echo "${indent}* [$title]($file_name)" >> "$SUMMARY_FILE"
                  fi
              done
          }

          generate_summary "." ""

      - name: Subir cambios si hay modificaciones
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add SUMMARY.md
          git diff --staged --quiet || (git commit -m "Actualizar SUMMARY.md" && git push)
