name: Update SUMMARY.md

on:
  push:
    branches:
      - main  # Cambia 'main' si usas otra rama

jobs:
  update-summary:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Generar nuevo SUMMARY.md
        run: |
          #!/bin/bash

          SUMMARY_FILE="SUMMARY.md"
          echo "# Summary" > "$SUMMARY_FILE"
          echo "" >> "$SUMMARY_FILE"

          generate_summary() {
              local dir="$1"
              local indent="$2"

              # Listar carpetas primero y archivos después
              local folders=($(find "$dir" -mindepth 1 -maxdepth 1 -type d | sort -f))
              local files=($(find "$dir" -mindepth 1 -maxdepth 1 -type f -name "*.md" ! -name "SUMMARY.md" | sort -f))

              # Agregar carpetas primero
              for folder in "${folders[@]}"; do
                  folder_name=$(basename "$folder")
                  echo "${indent}* **$folder_name/**" >> "$SUMMARY_FILE"
                  generate_summary "$folder" "$indent  "
              done

              # Agregar archivos Markdown después
              for file in "${files[@]}"; do
                  file_name=$(basename "$file" .md)
                  title=$(head -n 1 "$file" | sed 's/# //')
                  [[ -z "$title" ]] && title="$file_name"
