name: Update SUMMARY.md

on:
  push:
    branches:
      - main  # Cambia 'main' si usas otra rama

jobs:
  update-summary:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Generar nuevo SUMMARY.md
        run: |
          #!/bin/bash

          SUMMARY_FILE="SUMMARY.md"
          IGNORE_DIRS=("." ".git" ".github" ".gitbook" "node_modules" "__pycache__")

          echo "# Summary" > "$SUMMARY_FILE"
          echo "" >> "$SUMMARY_FILE"

          generate_summary() {
              local dir="$1"
              local indent="$2"

              for entry in "$dir"/*; do
                  local base_entry=$(basename "$entry")

                  # Ignorar directorios no deseados
                  if [[ " ${IGNORE_DIRS[@]} " =~ " ${base_entry} " ]]; then
                      continue
                  fi

                  if [[ -d "$entry" ]]; then
                      echo "${indent}- **$base_entry/**" >> "$SUMMARY_FILE"
                      generate_summary "$entry" "$indent  "
                  elif [[ -f "$entry" && "$entry" == *.md && "$entry" != "./SUMMARY.md" ]]; then
                      file_name=$(basename "$entry" .md)
                      title=$(head -n 1 "$entry" | sed 's/^# *//')
                      [[ -z "$title" ]] && title="$file_name"
                      relative_path="${entry#./}"
                      echo "${indent}- [$title]($relative_path)" >> "$SUMMARY_FILE"
                  fi
              done
          }

          generate_summary "." ""

      - name: Subir cambios si hay modificaciones
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add SUMMARY.md
          git diff --staged --quiet || (git commit -m "Actualizar SUMMARY.md" && git push)
