name: Update SUMMARY.md

on:
  push:
    branches:
      - main  # Cambia 'main' si usas otra rama

jobs:
  update-summary:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Generar nuevo SUMMARY.md
        run: |
          echo "# Summary" > SUMMARY.md
          echo "" >> SUMMARY.md
          find . -type f -name "*.md" ! -name "SUMMARY.md" | sort | while read -r file; do
              title=$(head -n 1 "$file" | sed 's/# //')
              if [[ -z "$title" ]]; then
                  title=$(basename "$file" .md)
              fi
              path="${file#./}"
              echo "- [$title]($path)" >> SUMMARY.md
          done

      - name: Subir cambios si hay modificaciones
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add SUMMARY.md
          git commit -m "Actualizar SUMMARY.md" || exit 0
          git push
